-- V10 OIDC/SSO（040）：身份映射 + 认证事件审计（追加型）。
-- V9 已被 039 角色/authz_events 占用；本刀取 V10。

CREATE TABLE IF NOT EXISTS identity_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer VARCHAR(512) NOT NULL,
    subject VARCHAR(512) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(320),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_identity_mappings_issuer_subject UNIQUE (issuer, subject)
);

CREATE INDEX IF NOT EXISTS idx_identity_mappings_username ON identity_mappings (username);

CREATE TABLE IF NOT EXISTS auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    principal_id VARCHAR(128),
    detail VARCHAR(1024),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_events_created_at ON auth_events (created_at);
CREATE INDEX IF NOT EXISTS idx_auth_events_type_created ON auth_events (event_type, created_at);
