-- V11 资产治理（041）：侧车变更审计（追加型）。
-- V10 已被 040 OIDC 占用；本刀取 V11。

CREATE TABLE IF NOT EXISTS asset_governance_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(128) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    change_summary VARCHAR(512) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_asset_gov_events_created ON asset_governance_events (created_at);
