-- V1 基线（025-pluggable-storage，PostgreSQL 方言）：完整最终结构一步到位——等价于 SQLite 侧 V1~V5
-- 收敛后的结构（含全部后加列与索引）。PG 是新增部署选项、无存量历史，故无 V2~V5。
-- 转写规则（data-model.md）：INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS
-- IDENTITY；BOOLEAN DEFAULT 1/0 → TRUE/FALSE；BLOB → BYTEA；REAL → DOUBLE PRECISION；
-- TIMESTAMP → TIMESTAMPTZ（实体侧 Instant 的时刻语义，跨时区部署正确）。

-- llm_calls：LLM 调用审计（宪法 V：Day One 落库）
CREATE TABLE IF NOT EXISTS llm_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    cost_micros BIGINT,
    profile_name VARCHAR(255),
    trace_id VARCHAR(64),
    success BOOLEAN NOT NULL,
    error_message TEXT,
    duration_ms BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_llm_calls_session ON llm_calls (session_id);
CREATE INDEX IF NOT EXISTS idx_llm_calls_profile ON llm_calls (profile_name);
CREATE INDEX IF NOT EXISTS idx_llm_calls_trace ON llm_calls (trace_id);

-- tool_invocations：工具调用审计（宪法 V）
CREATE TABLE IF NOT EXISTS tool_invocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    input_json TEXT,
    result_json TEXT,
    profile_name VARCHAR(255),
    trace_id VARCHAR(64),
    success BOOLEAN NOT NULL,
    error_message TEXT,
    blocked_by VARCHAR(16),
    execution_backend VARCHAR(8),
    container_id VARCHAR(64),
    duration_ms BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_session ON tool_invocations (session_id);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_profile ON tool_invocations (profile_name);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_trace ON tool_invocations (trace_id);

-- sessions：会话元数据 + JSON 序列化的对话历史
CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(512) PRIMARY KEY,
    profile_name VARCHAR(255) NOT NULL,
    channel VARCHAR(64) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    messages_json TEXT,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    last_active_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sessions_profile ON sessions (profile_name);

-- scheduled_tasks：定时任务登记 + 运行状态
CREATE TABLE IF NOT EXISTS scheduled_tasks (
    schedule_id VARCHAR(36) PRIMARY KEY,
    profile_name VARCHAR(255) NOT NULL,
    schedule_key VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    cron VARCHAR(128) NOT NULL,
    zone VARCHAR(64),
    message TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    retired BOOLEAN NOT NULL DEFAULT FALSE,
    next_run_at TIMESTAMPTZ,
    last_run_at TIMESTAMPTZ,
    last_status VARCHAR(16),
    run_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (profile_name, schedule_key)
);

-- task_executions：定时任务执行历史
CREATE TABLE IF NOT EXISTS task_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id VARCHAR(36),
    legacy_task_key VARCHAR(255),
    legacy_migrated BOOLEAN NOT NULL DEFAULT FALSE,
    session_id VARCHAR(512),
    started_at TIMESTAMPTZ NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    duration_ms BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_task_executions_schedule ON task_executions (schedule_id);

-- agent_executions：Agent 维度执行历史
CREATE TABLE IF NOT EXISTS agent_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(255) NOT NULL,
    source VARCHAR(32) NOT NULL,
    session_id VARCHAR(512),
    trace_id VARCHAR(64),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    success BOOLEAN,
    error_message TEXT,
    duration_ms BIGINT
);
CREATE INDEX IF NOT EXISTS idx_agent_executions_agent ON agent_executions (agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_executions_trace ON agent_executions (trace_id);

-- memory_entries：长期记忆条目
CREATE TABLE IF NOT EXISTS memory_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(128) NOT NULL DEFAULT '__global__',
    scope VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_scope ON memory_entries (scope);
CREATE INDEX IF NOT EXISTS idx_memory_agent ON memory_entries (agent_name, scope);

-- memory_vectors：归档记忆向量索引（float32[] 小端序字节，编解码与库无关）
CREATE TABLE IF NOT EXISTS memory_vectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_hash VARCHAR(64) NOT NULL,
    agent_name VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    embedding BYTEA NOT NULL,
    dim INTEGER NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    entry_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (agent_name, entry_hash)
);
CREATE INDEX IF NOT EXISTS idx_memvec_agent ON memory_vectors (agent_name);

-- notify_channels：全局通知渠道注册表（config 敏感项 enc:v1: 密文，TEXT 两库无缝）
CREATE TABLE IF NOT EXISTS notify_channels (
    name VARCHAR(128) PRIMARY KEY,
    type VARCHAR(32) NOT NULL,
    url TEXT NOT NULL,
    config TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- providers：LLM Provider 动态注册表（api_key 密文落库，022）
CREATE TABLE IF NOT EXISTS providers (
    name VARCHAR(128) PRIMARY KEY,
    api_key TEXT,
    base_url TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- llm_pricing：模型定价（成本写时定格）
CREATE TABLE IF NOT EXISTS llm_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    prompt_price DOUBLE PRECISION,
    completion_price DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (provider, model)
);

-- sandbox_whitelist：Sandbox 白名单持久化（宪法 VI）
CREATE TABLE IF NOT EXISTS sandbox_whitelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(16) NOT NULL,
    entry_value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (category, entry_value)
);

-- web_users：管理台账号（密码只存 {bcrypt} 哈希）
CREATE TABLE IF NOT EXISTS web_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_web_users_username ON web_users (username);

-- web_sessions：浏览器登录 session
CREATE TABLE IF NOT EXISTS web_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL UNIQUE,
    username VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_web_sessions_session ON web_sessions (session_id);

-- knowledge_documents：知识文档索引状态
CREATE TABLE IF NOT EXISTS knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_name VARCHAR(128) NOT NULL,
    rel_path VARCHAR(512) NOT NULL,
    content_sha256 VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    failure_reason TEXT,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    generation INTEGER NOT NULL DEFAULT 0,
    indexed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (kb_name, rel_path, generation)
);
CREATE INDEX IF NOT EXISTS idx_kdoc_kb ON knowledge_documents (kb_name, generation);

-- knowledge_chunks：知识片段（embedding 为 float32[] 字节，检索走 Java 余弦）
CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    kb_name VARCHAR(128) NOT NULL,
    seq INTEGER NOT NULL,
    page_no INTEGER,
    content TEXT NOT NULL,
    embedding BYTEA,
    dim INTEGER,
    embedding_model VARCHAR(128),
    generation INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_kchunk_kb ON knowledge_chunks (kb_name, generation);
CREATE INDEX IF NOT EXISTS idx_kchunk_doc ON knowledge_chunks (document_id);

-- api_keys：REST API 机器调用凭证（只存 SHA-256 哈希）
CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    key_prefix VARCHAR(16) NOT NULL,
    key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
);

-- tool_policy_rules：工具策略（020）
CREATE TABLE IF NOT EXISTS tool_policy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type VARCHAR(16) NOT NULL,
    agent_name VARCHAR(255),
    pattern VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(255),
    UNIQUE (rule_type, agent_name, pattern)
);
