-- V6：流式 Run 工作台。不改 V1——存量 PG 已执行过基线，本版本只增列/表。
-- IF NOT EXISTS 覆盖曾被误写入 V1 的库（本 PR 早期改过基线）。

ALTER TABLE agent_executions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE agent_executions ADD COLUMN IF NOT EXISTS input_preview TEXT;
ALTER TABLE agent_executions ADD COLUMN IF NOT EXISTS cancel_requested_at TIMESTAMPTZ;
ALTER TABLE agent_executions ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE agent_executions ADD COLUMN IF NOT EXISTS stop_reason VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_agent_executions_started ON agent_executions (started_at, id);

UPDATE agent_executions SET status = 'RUNNING' WHERE status IS NULL AND ended_at IS NULL;
UPDATE agent_executions SET status = 'SUCCESS' WHERE status IS NULL AND success IS TRUE;
UPDATE agent_executions SET status = 'FAILED' WHERE status IS NULL AND ended_at IS NOT NULL;
UPDATE agent_executions SET updated_at = COALESCE(ended_at, started_at) WHERE updated_at IS NULL;

CREATE TABLE IF NOT EXISTS agent_run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL,
    type VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    payload_json TEXT NOT NULL,
    UNIQUE (run_id, sequence)
);
CREATE INDEX IF NOT EXISTS idx_agent_run_events_run_seq ON agent_run_events (run_id, sequence);
